/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.Genre;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenreRecord extends UpdatableRecordImpl<GenreRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.genre.genre_id</code>.
     */
    public void setGenreId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.genre.genre_id</code>.
     */
    public Integer getGenreId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.genre.genre_name</code>.
     */
    public void setGenreName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.genre.genre_name</code>.
     */
    public String getGenreName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Genre.GENRE.GENRE_ID;
    }

    @Override
    public Field<String> field2() {
        return Genre.GENRE.GENRE_NAME;
    }

    @Override
    public Integer component1() {
        return getGenreId();
    }

    @Override
    public String component2() {
        return getGenreName();
    }

    @Override
    public Integer value1() {
        return getGenreId();
    }

    @Override
    public String value2() {
        return getGenreName();
    }

    @Override
    public GenreRecord value1(Integer value) {
        setGenreId(value);
        return this;
    }

    @Override
    public GenreRecord value2(String value) {
        setGenreName(value);
        return this;
    }

    @Override
    public GenreRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenreRecord
     */
    public GenreRecord() {
        super(Genre.GENRE);
    }

    /**
     * Create a detached, initialised GenreRecord
     */
    public GenreRecord(Integer genreId, String genreName) {
        super(Genre.GENRE);

        setGenreId(genreId);
        setGenreName(genreName);
    }
}
