/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.Keyword;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KeywordRecord extends UpdatableRecordImpl<KeywordRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.keyword.keyword_id</code>.
     */
    public void setKeywordId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.keyword.keyword_id</code>.
     */
    public Integer getKeywordId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.keyword.keyword_name</code>.
     */
    public void setKeywordName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.keyword.keyword_name</code>.
     */
    public String getKeywordName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Keyword.KEYWORD.KEYWORD_ID;
    }

    @Override
    public Field<String> field2() {
        return Keyword.KEYWORD.KEYWORD_NAME;
    }

    @Override
    public Integer component1() {
        return getKeywordId();
    }

    @Override
    public String component2() {
        return getKeywordName();
    }

    @Override
    public Integer value1() {
        return getKeywordId();
    }

    @Override
    public String value2() {
        return getKeywordName();
    }

    @Override
    public KeywordRecord value1(Integer value) {
        setKeywordId(value);
        return this;
    }

    @Override
    public KeywordRecord value2(String value) {
        setKeywordName(value);
        return this;
    }

    @Override
    public KeywordRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KeywordRecord
     */
    public KeywordRecord() {
        super(Keyword.KEYWORD);
    }

    /**
     * Create a detached, initialised KeywordRecord
     */
    public KeywordRecord(Integer keywordId, String keywordName) {
        super(Keyword.KEYWORD);

        setKeywordId(keywordId);
        setKeywordName(keywordName);
    }
}
