/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.LanguageRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageRoleRecord extends UpdatableRecordImpl<LanguageRoleRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.language_role.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.language_role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.language_role.language_role</code>.
     */
    public void setLanguageRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.language_role.language_role</code>.
     */
    public String getLanguageRole() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LanguageRole.LANGUAGE_ROLE.ROLE_ID;
    }

    @Override
    public Field<String> field2() {
        return LanguageRole.LANGUAGE_ROLE.LANGUAGE_ROLE_;
    }

    @Override
    public Integer component1() {
        return getRoleId();
    }

    @Override
    public String component2() {
        return getLanguageRole();
    }

    @Override
    public Integer value1() {
        return getRoleId();
    }

    @Override
    public String value2() {
        return getLanguageRole();
    }

    @Override
    public LanguageRoleRecord value1(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public LanguageRoleRecord value2(String value) {
        setLanguageRole(value);
        return this;
    }

    @Override
    public LanguageRoleRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageRoleRecord
     */
    public LanguageRoleRecord() {
        super(LanguageRole.LANGUAGE_ROLE);
    }

    /**
     * Create a detached, initialised LanguageRoleRecord
     */
    public LanguageRoleRecord(Integer roleId, String languageRole) {
        super(LanguageRole.LANGUAGE_ROLE);

        setRoleId(roleId);
        setLanguageRole(languageRole);
    }
}
