/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.MovieCast;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieCastRecord extends TableRecordImpl<MovieCastRecord> implements Record5<Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.movie_cast.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.movie_cast.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.movie_cast.person_id</code>.
     */
    public void setPersonId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.movie_cast.person_id</code>.
     */
    public Integer getPersonId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>movies.movie_cast.character_name</code>.
     */
    public void setCharacterName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>movies.movie_cast.character_name</code>.
     */
    public String getCharacterName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>movies.movie_cast.gender_id</code>.
     */
    public void setGenderId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>movies.movie_cast.gender_id</code>.
     */
    public Integer getGenderId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>movies.movie_cast.cast_order</code>.
     */
    public void setCastOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>movies.movie_cast.cast_order</code>.
     */
    public Integer getCastOrder() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MovieCast.MOVIE_CAST.MOVIE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return MovieCast.MOVIE_CAST.PERSON_ID;
    }

    @Override
    public Field<String> field3() {
        return MovieCast.MOVIE_CAST.CHARACTER_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return MovieCast.MOVIE_CAST.GENDER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return MovieCast.MOVIE_CAST.CAST_ORDER;
    }

    @Override
    public Integer component1() {
        return getMovieId();
    }

    @Override
    public Integer component2() {
        return getPersonId();
    }

    @Override
    public String component3() {
        return getCharacterName();
    }

    @Override
    public Integer component4() {
        return getGenderId();
    }

    @Override
    public Integer component5() {
        return getCastOrder();
    }

    @Override
    public Integer value1() {
        return getMovieId();
    }

    @Override
    public Integer value2() {
        return getPersonId();
    }

    @Override
    public String value3() {
        return getCharacterName();
    }

    @Override
    public Integer value4() {
        return getGenderId();
    }

    @Override
    public Integer value5() {
        return getCastOrder();
    }

    @Override
    public MovieCastRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    @Override
    public MovieCastRecord value2(Integer value) {
        setPersonId(value);
        return this;
    }

    @Override
    public MovieCastRecord value3(String value) {
        setCharacterName(value);
        return this;
    }

    @Override
    public MovieCastRecord value4(Integer value) {
        setGenderId(value);
        return this;
    }

    @Override
    public MovieCastRecord value5(Integer value) {
        setCastOrder(value);
        return this;
    }

    @Override
    public MovieCastRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieCastRecord
     */
    public MovieCastRecord() {
        super(MovieCast.MOVIE_CAST);
    }

    /**
     * Create a detached, initialised MovieCastRecord
     */
    public MovieCastRecord(Integer movieId, Integer personId, String characterName, Integer genderId, Integer castOrder) {
        super(MovieCast.MOVIE_CAST);

        setMovieId(movieId);
        setPersonId(personId);
        setCharacterName(characterName);
        setGenderId(genderId);
        setCastOrder(castOrder);
    }
}
