/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.MovieGenres;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieGenresRecord extends TableRecordImpl<MovieGenresRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.movie_genres.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.movie_genres.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.movie_genres.genre_id</code>.
     */
    public void setGenreId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.movie_genres.genre_id</code>.
     */
    public Integer getGenreId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MovieGenres.MOVIE_GENRES.MOVIE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return MovieGenres.MOVIE_GENRES.GENRE_ID;
    }

    @Override
    public Integer component1() {
        return getMovieId();
    }

    @Override
    public Integer component2() {
        return getGenreId();
    }

    @Override
    public Integer value1() {
        return getMovieId();
    }

    @Override
    public Integer value2() {
        return getGenreId();
    }

    @Override
    public MovieGenresRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    @Override
    public MovieGenresRecord value2(Integer value) {
        setGenreId(value);
        return this;
    }

    @Override
    public MovieGenresRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieGenresRecord
     */
    public MovieGenresRecord() {
        super(MovieGenres.MOVIE_GENRES);
    }

    /**
     * Create a detached, initialised MovieGenresRecord
     */
    public MovieGenresRecord(Integer movieId, Integer genreId) {
        super(MovieGenres.MOVIE_GENRES);

        setMovieId(movieId);
        setGenreId(genreId);
    }
}
