/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.MovieCompany;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieCompanyRecord extends TableRecordImpl<MovieCompanyRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.movie_company.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.movie_company.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.movie_company.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.movie_company.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MovieCompany.MOVIE_COMPANY.MOVIE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return MovieCompany.MOVIE_COMPANY.COMPANY_ID;
    }

    @Override
    public Integer component1() {
        return getMovieId();
    }

    @Override
    public Integer component2() {
        return getCompanyId();
    }

    @Override
    public Integer value1() {
        return getMovieId();
    }

    @Override
    public Integer value2() {
        return getCompanyId();
    }

    @Override
    public MovieCompanyRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    @Override
    public MovieCompanyRecord value2(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public MovieCompanyRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieCompanyRecord
     */
    public MovieCompanyRecord() {
        super(MovieCompany.MOVIE_COMPANY);
    }

    /**
     * Create a detached, initialised MovieCompanyRecord
     */
    public MovieCompanyRecord(Integer movieId, Integer companyId) {
        super(MovieCompany.MOVIE_COMPANY);

        setMovieId(movieId);
        setCompanyId(companyId);
    }
}
