/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.MovieLanguages;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieLanguagesRecord extends TableRecordImpl<MovieLanguagesRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.movie_languages.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.movie_languages.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.movie_languages.language_id</code>.
     */
    public void setLanguageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.movie_languages.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>movies.movie_languages.language_role_id</code>.
     */
    public void setLanguageRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>movies.movie_languages.language_role_id</code>.
     */
    public Integer getLanguageRoleId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MovieLanguages.MOVIE_LANGUAGES.MOVIE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return MovieLanguages.MOVIE_LANGUAGES.LANGUAGE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return MovieLanguages.MOVIE_LANGUAGES.LANGUAGE_ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getMovieId();
    }

    @Override
    public Integer component2() {
        return getLanguageId();
    }

    @Override
    public Integer component3() {
        return getLanguageRoleId();
    }

    @Override
    public Integer value1() {
        return getMovieId();
    }

    @Override
    public Integer value2() {
        return getLanguageId();
    }

    @Override
    public Integer value3() {
        return getLanguageRoleId();
    }

    @Override
    public MovieLanguagesRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    @Override
    public MovieLanguagesRecord value2(Integer value) {
        setLanguageId(value);
        return this;
    }

    @Override
    public MovieLanguagesRecord value3(Integer value) {
        setLanguageRoleId(value);
        return this;
    }

    @Override
    public MovieLanguagesRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieLanguagesRecord
     */
    public MovieLanguagesRecord() {
        super(MovieLanguages.MOVIE_LANGUAGES);
    }

    /**
     * Create a detached, initialised MovieLanguagesRecord
     */
    public MovieLanguagesRecord(Integer movieId, Integer languageId, Integer languageRoleId) {
        super(MovieLanguages.MOVIE_LANGUAGES);

        setMovieId(movieId);
        setLanguageId(languageId);
        setLanguageRoleId(languageRoleId);
    }
}
