/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.Movie;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieRecord extends UpdatableRecordImpl<MovieRecord> implements Record13<Integer, String, Integer, String, String, BigDecimal, LocalDate, Long, Integer, String, String, BigDecimal, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.movie.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.movie.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.movie.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.movie.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>movies.movie.budget</code>.
     */
    public void setBudget(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>movies.movie.budget</code>.
     */
    public Integer getBudget() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>movies.movie.homepage</code>.
     */
    public void setHomepage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>movies.movie.homepage</code>.
     */
    public String getHomepage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>movies.movie.overview</code>.
     */
    public void setOverview(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>movies.movie.overview</code>.
     */
    public String getOverview() {
        return (String) get(4);
    }

    /**
     * Setter for <code>movies.movie.popularity</code>.
     */
    public void setPopularity(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>movies.movie.popularity</code>.
     */
    public BigDecimal getPopularity() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>movies.movie.release_date</code>.
     */
    public void setReleaseDate(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>movies.movie.release_date</code>.
     */
    public LocalDate getReleaseDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>movies.movie.revenue</code>.
     */
    public void setRevenue(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>movies.movie.revenue</code>.
     */
    public Long getRevenue() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>movies.movie.runtime</code>.
     */
    public void setRuntime(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>movies.movie.runtime</code>.
     */
    public Integer getRuntime() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>movies.movie.movie_status</code>.
     */
    public void setMovieStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>movies.movie.movie_status</code>.
     */
    public String getMovieStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>movies.movie.tagline</code>.
     */
    public void setTagline(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>movies.movie.tagline</code>.
     */
    public String getTagline() {
        return (String) get(10);
    }

    /**
     * Setter for <code>movies.movie.vote_average</code>.
     */
    public void setVoteAverage(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>movies.movie.vote_average</code>.
     */
    public BigDecimal getVoteAverage() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>movies.movie.vote_count</code>.
     */
    public void setVoteCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>movies.movie.vote_count</code>.
     */
    public Integer getVoteCount() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, Integer, String, String, BigDecimal, LocalDate, Long, Integer, String, String, BigDecimal, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, Integer, String, String, BigDecimal, LocalDate, Long, Integer, String, String, BigDecimal, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Movie.MOVIE.MOVIE_ID;
    }

    @Override
    public Field<String> field2() {
        return Movie.MOVIE.TITLE;
    }

    @Override
    public Field<Integer> field3() {
        return Movie.MOVIE.BUDGET;
    }

    @Override
    public Field<String> field4() {
        return Movie.MOVIE.HOMEPAGE;
    }

    @Override
    public Field<String> field5() {
        return Movie.MOVIE.OVERVIEW;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Movie.MOVIE.POPULARITY;
    }

    @Override
    public Field<LocalDate> field7() {
        return Movie.MOVIE.RELEASE_DATE;
    }

    @Override
    public Field<Long> field8() {
        return Movie.MOVIE.REVENUE;
    }

    @Override
    public Field<Integer> field9() {
        return Movie.MOVIE.RUNTIME;
    }

    @Override
    public Field<String> field10() {
        return Movie.MOVIE.MOVIE_STATUS;
    }

    @Override
    public Field<String> field11() {
        return Movie.MOVIE.TAGLINE;
    }

    @Override
    public Field<BigDecimal> field12() {
        return Movie.MOVIE.VOTE_AVERAGE;
    }

    @Override
    public Field<Integer> field13() {
        return Movie.MOVIE.VOTE_COUNT;
    }

    @Override
    public Integer component1() {
        return getMovieId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public Integer component3() {
        return getBudget();
    }

    @Override
    public String component4() {
        return getHomepage();
    }

    @Override
    public String component5() {
        return getOverview();
    }

    @Override
    public BigDecimal component6() {
        return getPopularity();
    }

    @Override
    public LocalDate component7() {
        return getReleaseDate();
    }

    @Override
    public Long component8() {
        return getRevenue();
    }

    @Override
    public Integer component9() {
        return getRuntime();
    }

    @Override
    public String component10() {
        return getMovieStatus();
    }

    @Override
    public String component11() {
        return getTagline();
    }

    @Override
    public BigDecimal component12() {
        return getVoteAverage();
    }

    @Override
    public Integer component13() {
        return getVoteCount();
    }

    @Override
    public Integer value1() {
        return getMovieId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public Integer value3() {
        return getBudget();
    }

    @Override
    public String value4() {
        return getHomepage();
    }

    @Override
    public String value5() {
        return getOverview();
    }

    @Override
    public BigDecimal value6() {
        return getPopularity();
    }

    @Override
    public LocalDate value7() {
        return getReleaseDate();
    }

    @Override
    public Long value8() {
        return getRevenue();
    }

    @Override
    public Integer value9() {
        return getRuntime();
    }

    @Override
    public String value10() {
        return getMovieStatus();
    }

    @Override
    public String value11() {
        return getTagline();
    }

    @Override
    public BigDecimal value12() {
        return getVoteAverage();
    }

    @Override
    public Integer value13() {
        return getVoteCount();
    }

    @Override
    public MovieRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    @Override
    public MovieRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public MovieRecord value3(Integer value) {
        setBudget(value);
        return this;
    }

    @Override
    public MovieRecord value4(String value) {
        setHomepage(value);
        return this;
    }

    @Override
    public MovieRecord value5(String value) {
        setOverview(value);
        return this;
    }

    @Override
    public MovieRecord value6(BigDecimal value) {
        setPopularity(value);
        return this;
    }

    @Override
    public MovieRecord value7(LocalDate value) {
        setReleaseDate(value);
        return this;
    }

    @Override
    public MovieRecord value8(Long value) {
        setRevenue(value);
        return this;
    }

    @Override
    public MovieRecord value9(Integer value) {
        setRuntime(value);
        return this;
    }

    @Override
    public MovieRecord value10(String value) {
        setMovieStatus(value);
        return this;
    }

    @Override
    public MovieRecord value11(String value) {
        setTagline(value);
        return this;
    }

    @Override
    public MovieRecord value12(BigDecimal value) {
        setVoteAverage(value);
        return this;
    }

    @Override
    public MovieRecord value13(Integer value) {
        setVoteCount(value);
        return this;
    }

    @Override
    public MovieRecord values(Integer value1, String value2, Integer value3, String value4, String value5, BigDecimal value6, LocalDate value7, Long value8, Integer value9, String value10, String value11, BigDecimal value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieRecord
     */
    public MovieRecord() {
        super(Movie.MOVIE);
    }

    /**
     * Create a detached, initialised MovieRecord
     */
    public MovieRecord(Integer movieId, String title, Integer budget, String homepage, String overview, BigDecimal popularity, LocalDate releaseDate, Long revenue, Integer runtime, String movieStatus, String tagline, BigDecimal voteAverage, Integer voteCount) {
        super(Movie.MOVIE);

        setMovieId(movieId);
        setTitle(title);
        setBudget(budget);
        setHomepage(homepage);
        setOverview(overview);
        setPopularity(popularity);
        setReleaseDate(releaseDate);
        setRevenue(revenue);
        setRuntime(runtime);
        setMovieStatus(movieStatus);
        setTagline(tagline);
        setVoteAverage(voteAverage);
        setVoteCount(voteCount);
    }
}
