/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.Person;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonRecord extends UpdatableRecordImpl<PersonRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.person.person_id</code>.
     */
    public void setPersonId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.person.person_id</code>.
     */
    public Integer getPersonId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.person.person_name</code>.
     */
    public void setPersonName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.person.person_name</code>.
     */
    public String getPersonName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Person.PERSON.PERSON_ID;
    }

    @Override
    public Field<String> field2() {
        return Person.PERSON.PERSON_NAME;
    }

    @Override
    public Integer component1() {
        return getPersonId();
    }

    @Override
    public String component2() {
        return getPersonName();
    }

    @Override
    public Integer value1() {
        return getPersonId();
    }

    @Override
    public String value2() {
        return getPersonName();
    }

    @Override
    public PersonRecord value1(Integer value) {
        setPersonId(value);
        return this;
    }

    @Override
    public PersonRecord value2(String value) {
        setPersonName(value);
        return this;
    }

    @Override
    public PersonRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonRecord
     */
    public PersonRecord() {
        super(Person.PERSON);
    }

    /**
     * Create a detached, initialised PersonRecord
     */
    public PersonRecord(Integer personId, String personName) {
        super(Person.PERSON);

        setPersonId(personId);
        setPersonName(personName);
    }
}
