/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.ProductionCompany;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductionCompanyRecord extends UpdatableRecordImpl<ProductionCompanyRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.production_company.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.production_company.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.production_company.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.production_company.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProductionCompany.PRODUCTION_COMPANY.COMPANY_ID;
    }

    @Override
    public Field<String> field2() {
        return ProductionCompany.PRODUCTION_COMPANY.COMPANY_NAME;
    }

    @Override
    public Integer component1() {
        return getCompanyId();
    }

    @Override
    public String component2() {
        return getCompanyName();
    }

    @Override
    public Integer value1() {
        return getCompanyId();
    }

    @Override
    public String value2() {
        return getCompanyName();
    }

    @Override
    public ProductionCompanyRecord value1(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public ProductionCompanyRecord value2(String value) {
        setCompanyName(value);
        return this;
    }

    @Override
    public ProductionCompanyRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductionCompanyRecord
     */
    public ProductionCompanyRecord() {
        super(ProductionCompany.PRODUCTION_COMPANY);
    }

    /**
     * Create a detached, initialised ProductionCompanyRecord
     */
    public ProductionCompanyRecord(Integer companyId, String companyName) {
        super(ProductionCompany.PRODUCTION_COMPANY);

        setCompanyId(companyId);
        setCompanyName(companyName);
    }
}
