/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables.records;


import com.example.springboot.jooqGenerated.tables.ProductionCountry;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductionCountryRecord extends TableRecordImpl<ProductionCountryRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>movies.production_country.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>movies.production_country.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>movies.production_country.country_id</code>.
     */
    public void setCountryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>movies.production_country.country_id</code>.
     */
    public Integer getCountryId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProductionCountry.PRODUCTION_COUNTRY.MOVIE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ProductionCountry.PRODUCTION_COUNTRY.COUNTRY_ID;
    }

    @Override
    public Integer component1() {
        return getMovieId();
    }

    @Override
    public Integer component2() {
        return getCountryId();
    }

    @Override
    public Integer value1() {
        return getMovieId();
    }

    @Override
    public Integer value2() {
        return getCountryId();
    }

    @Override
    public ProductionCountryRecord value1(Integer value) {
        setMovieId(value);
        return this;
    }

    @Override
    public ProductionCountryRecord value2(Integer value) {
        setCountryId(value);
        return this;
    }

    @Override
    public ProductionCountryRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductionCountryRecord
     */
    public ProductionCountryRecord() {
        super(ProductionCountry.PRODUCTION_COUNTRY);
    }

    /**
     * Create a detached, initialised ProductionCountryRecord
     */
    public ProductionCountryRecord(Integer movieId, Integer countryId) {
        super(ProductionCountry.PRODUCTION_COUNTRY);

        setMovieId(movieId);
        setCountryId(countryId);
    }
}
