/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated;


import com.example.springboot.jooqGenerated.tables.Country;
import com.example.springboot.jooqGenerated.tables.Department;
import com.example.springboot.jooqGenerated.tables.Gender;
import com.example.springboot.jooqGenerated.tables.Genre;
import com.example.springboot.jooqGenerated.tables.Keyword;
import com.example.springboot.jooqGenerated.tables.Language;
import com.example.springboot.jooqGenerated.tables.LanguageRole;
import com.example.springboot.jooqGenerated.tables.Movie;
import com.example.springboot.jooqGenerated.tables.MovieCast;
import com.example.springboot.jooqGenerated.tables.MovieCompany;
import com.example.springboot.jooqGenerated.tables.MovieCrew;
import com.example.springboot.jooqGenerated.tables.MovieGenres;
import com.example.springboot.jooqGenerated.tables.MovieKeywords;
import com.example.springboot.jooqGenerated.tables.MovieLanguages;
import com.example.springboot.jooqGenerated.tables.Person;
import com.example.springboot.jooqGenerated.tables.ProductionCompany;
import com.example.springboot.jooqGenerated.tables.ProductionCountry;


/**
 * Convenience access to all tables in movies.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>movies.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>movies.department</code>.
     */
    public static final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>movies.gender</code>.
     */
    public static final Gender GENDER = Gender.GENDER;

    /**
     * The table <code>movies.genre</code>.
     */
    public static final Genre GENRE = Genre.GENRE;

    /**
     * The table <code>movies.keyword</code>.
     */
    public static final Keyword KEYWORD = Keyword.KEYWORD;

    /**
     * The table <code>movies.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>movies.language_role</code>.
     */
    public static final LanguageRole LANGUAGE_ROLE = LanguageRole.LANGUAGE_ROLE;

    /**
     * The table <code>movies.movie</code>.
     */
    public static final Movie MOVIE = Movie.MOVIE;

    /**
     * The table <code>movies.movie_cast</code>.
     */
    public static final MovieCast MOVIE_CAST = MovieCast.MOVIE_CAST;

    /**
     * The table <code>movies.movie_company</code>.
     */
    public static final MovieCompany MOVIE_COMPANY = MovieCompany.MOVIE_COMPANY;

    /**
     * The table <code>movies.movie_crew</code>.
     */
    public static final MovieCrew MOVIE_CREW = MovieCrew.MOVIE_CREW;

    /**
     * The table <code>movies.movie_genres</code>.
     */
    public static final MovieGenres MOVIE_GENRES = MovieGenres.MOVIE_GENRES;

    /**
     * The table <code>movies.movie_keywords</code>.
     */
    public static final MovieKeywords MOVIE_KEYWORDS = MovieKeywords.MOVIE_KEYWORDS;

    /**
     * The table <code>movies.movie_languages</code>.
     */
    public static final MovieLanguages MOVIE_LANGUAGES = MovieLanguages.MOVIE_LANGUAGES;

    /**
     * The table <code>movies.person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>movies.production_company</code>.
     */
    public static final ProductionCompany PRODUCTION_COMPANY = ProductionCompany.PRODUCTION_COMPANY;

    /**
     * The table <code>movies.production_country</code>.
     */
    public static final ProductionCountry PRODUCTION_COUNTRY = ProductionCountry.PRODUCTION_COUNTRY;
}
