/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables;


import com.example.springboot.jooqGenerated.Keys;
import com.example.springboot.jooqGenerated.Movies;
import com.example.springboot.jooqGenerated.tables.records.GenreRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Genre extends TableImpl<GenreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>movies.genre</code>
     */
    public static final Genre GENRE = new Genre();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenreRecord> getRecordType() {
        return GenreRecord.class;
    }

    /**
     * The column <code>movies.genre.genre_id</code>.
     */
    public final TableField<GenreRecord, Integer> GENRE_ID = createField(DSL.name("genre_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>movies.genre.genre_name</code>.
     */
    public final TableField<GenreRecord, String> GENRE_NAME = createField(DSL.name("genre_name"), SQLDataType.VARCHAR(100), this, "");

    private Genre(Name alias, Table<GenreRecord> aliased) {
        this(alias, aliased, null);
    }

    private Genre(Name alias, Table<GenreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>movies.genre</code> table reference
     */
    public Genre(String alias) {
        this(DSL.name(alias), GENRE);
    }

    /**
     * Create an aliased <code>movies.genre</code> table reference
     */
    public Genre(Name alias) {
        this(alias, GENRE);
    }

    /**
     * Create a <code>movies.genre</code> table reference
     */
    public Genre() {
        this(DSL.name("genre"), null);
    }

    public <O extends Record> Genre(Table<O> child, ForeignKey<O, GenreRecord> key) {
        super(child, key, GENRE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Movies.MOVIES;
    }

    @Override
    public UniqueKey<GenreRecord> getPrimaryKey() {
        return Keys.KEY_GENRE_PRIMARY;
    }

    @Override
    public Genre as(String alias) {
        return new Genre(DSL.name(alias), this);
    }

    @Override
    public Genre as(Name alias) {
        return new Genre(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Genre rename(String name) {
        return new Genre(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genre rename(Name name) {
        return new Genre(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
