/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables;


import com.example.springboot.jooqGenerated.Keys;
import com.example.springboot.jooqGenerated.Movies;
import com.example.springboot.jooqGenerated.tables.records.MovieKeywordsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieKeywords extends TableImpl<MovieKeywordsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>movies.movie_keywords</code>
     */
    public static final MovieKeywords MOVIE_KEYWORDS = new MovieKeywords();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieKeywordsRecord> getRecordType() {
        return MovieKeywordsRecord.class;
    }

    /**
     * The column <code>movies.movie_keywords.movie_id</code>.
     */
    public final TableField<MovieKeywordsRecord, Integer> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.movie_keywords.keyword_id</code>.
     */
    public final TableField<MovieKeywordsRecord, Integer> KEYWORD_ID = createField(DSL.name("keyword_id"), SQLDataType.INTEGER, this, "");

    private MovieKeywords(Name alias, Table<MovieKeywordsRecord> aliased) {
        this(alias, aliased, null);
    }

    private MovieKeywords(Name alias, Table<MovieKeywordsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>movies.movie_keywords</code> table reference
     */
    public MovieKeywords(String alias) {
        this(DSL.name(alias), MOVIE_KEYWORDS);
    }

    /**
     * Create an aliased <code>movies.movie_keywords</code> table reference
     */
    public MovieKeywords(Name alias) {
        this(alias, MOVIE_KEYWORDS);
    }

    /**
     * Create a <code>movies.movie_keywords</code> table reference
     */
    public MovieKeywords() {
        this(DSL.name("movie_keywords"), null);
    }

    public <O extends Record> MovieKeywords(Table<O> child, ForeignKey<O, MovieKeywordsRecord> key) {
        super(child, key, MOVIE_KEYWORDS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Movies.MOVIES;
    }

    @Override
    public List<ForeignKey<MovieKeywordsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_MK_MOVIE, Keys.FK_MK_KEYWORD);
    }

    private transient Movie _movie;
    private transient Keyword _keyword;

    /**
     * Get the implicit join path to the <code>movies.movie</code> table.
     */
    public Movie movie() {
        if (_movie == null)
            _movie = new Movie(this, Keys.FK_MK_MOVIE);

        return _movie;
    }

    /**
     * Get the implicit join path to the <code>movies.keyword</code> table.
     */
    public Keyword keyword() {
        if (_keyword == null)
            _keyword = new Keyword(this, Keys.FK_MK_KEYWORD);

        return _keyword;
    }

    @Override
    public MovieKeywords as(String alias) {
        return new MovieKeywords(DSL.name(alias), this);
    }

    @Override
    public MovieKeywords as(Name alias) {
        return new MovieKeywords(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieKeywords rename(String name) {
        return new MovieKeywords(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieKeywords rename(Name name) {
        return new MovieKeywords(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
