/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables;


import com.example.springboot.jooqGenerated.Keys;
import com.example.springboot.jooqGenerated.Movies;
import com.example.springboot.jooqGenerated.tables.records.MovieGenresRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieGenres extends TableImpl<MovieGenresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>movies.movie_genres</code>
     */
    public static final MovieGenres MOVIE_GENRES = new MovieGenres();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieGenresRecord> getRecordType() {
        return MovieGenresRecord.class;
    }

    /**
     * The column <code>movies.movie_genres.movie_id</code>.
     */
    public final TableField<MovieGenresRecord, Integer> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.movie_genres.genre_id</code>.
     */
    public final TableField<MovieGenresRecord, Integer> GENRE_ID = createField(DSL.name("genre_id"), SQLDataType.INTEGER, this, "");

    private MovieGenres(Name alias, Table<MovieGenresRecord> aliased) {
        this(alias, aliased, null);
    }

    private MovieGenres(Name alias, Table<MovieGenresRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>movies.movie_genres</code> table reference
     */
    public MovieGenres(String alias) {
        this(DSL.name(alias), MOVIE_GENRES);
    }

    /**
     * Create an aliased <code>movies.movie_genres</code> table reference
     */
    public MovieGenres(Name alias) {
        this(alias, MOVIE_GENRES);
    }

    /**
     * Create a <code>movies.movie_genres</code> table reference
     */
    public MovieGenres() {
        this(DSL.name("movie_genres"), null);
    }

    public <O extends Record> MovieGenres(Table<O> child, ForeignKey<O, MovieGenresRecord> key) {
        super(child, key, MOVIE_GENRES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Movies.MOVIES;
    }

    @Override
    public List<ForeignKey<MovieGenresRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_MG_MOVIE, Keys.FK_MG_GENRE);
    }

    private transient Movie _movie;
    private transient Genre _genre;

    /**
     * Get the implicit join path to the <code>movies.movie</code> table.
     */
    public Movie movie() {
        if (_movie == null)
            _movie = new Movie(this, Keys.FK_MG_MOVIE);

        return _movie;
    }

    /**
     * Get the implicit join path to the <code>movies.genre</code> table.
     */
    public Genre genre() {
        if (_genre == null)
            _genre = new Genre(this, Keys.FK_MG_GENRE);

        return _genre;
    }

    @Override
    public MovieGenres as(String alias) {
        return new MovieGenres(DSL.name(alias), this);
    }

    @Override
    public MovieGenres as(Name alias) {
        return new MovieGenres(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieGenres rename(String name) {
        return new MovieGenres(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieGenres rename(Name name) {
        return new MovieGenres(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
