/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables;


import com.example.springboot.jooqGenerated.Keys;
import com.example.springboot.jooqGenerated.Movies;
import com.example.springboot.jooqGenerated.tables.records.MovieCrewRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieCrew extends TableImpl<MovieCrewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>movies.movie_crew</code>
     */
    public static final MovieCrew MOVIE_CREW = new MovieCrew();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieCrewRecord> getRecordType() {
        return MovieCrewRecord.class;
    }

    /**
     * The column <code>movies.movie_crew.movie_id</code>.
     */
    public final TableField<MovieCrewRecord, Integer> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.movie_crew.person_id</code>.
     */
    public final TableField<MovieCrewRecord, Integer> PERSON_ID = createField(DSL.name("person_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.movie_crew.department_id</code>.
     */
    public final TableField<MovieCrewRecord, Integer> DEPARTMENT_ID = createField(DSL.name("department_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.movie_crew.job</code>.
     */
    public final TableField<MovieCrewRecord, String> JOB = createField(DSL.name("job"), SQLDataType.VARCHAR(200), this, "");

    private MovieCrew(Name alias, Table<MovieCrewRecord> aliased) {
        this(alias, aliased, null);
    }

    private MovieCrew(Name alias, Table<MovieCrewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>movies.movie_crew</code> table reference
     */
    public MovieCrew(String alias) {
        this(DSL.name(alias), MOVIE_CREW);
    }

    /**
     * Create an aliased <code>movies.movie_crew</code> table reference
     */
    public MovieCrew(Name alias) {
        this(alias, MOVIE_CREW);
    }

    /**
     * Create a <code>movies.movie_crew</code> table reference
     */
    public MovieCrew() {
        this(DSL.name("movie_crew"), null);
    }

    public <O extends Record> MovieCrew(Table<O> child, ForeignKey<O, MovieCrewRecord> key) {
        super(child, key, MOVIE_CREW);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Movies.MOVIES;
    }

    @Override
    public List<ForeignKey<MovieCrewRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_MCR_MOVIE, Keys.FK_MCR_PER, Keys.FK_MCR_DEPT);
    }

    private transient Movie _movie;
    private transient Person _person;
    private transient Department _department;

    /**
     * Get the implicit join path to the <code>movies.movie</code> table.
     */
    public Movie movie() {
        if (_movie == null)
            _movie = new Movie(this, Keys.FK_MCR_MOVIE);

        return _movie;
    }

    /**
     * Get the implicit join path to the <code>movies.person</code> table.
     */
    public Person person() {
        if (_person == null)
            _person = new Person(this, Keys.FK_MCR_PER);

        return _person;
    }

    /**
     * Get the implicit join path to the <code>movies.department</code> table.
     */
    public Department department() {
        if (_department == null)
            _department = new Department(this, Keys.FK_MCR_DEPT);

        return _department;
    }

    @Override
    public MovieCrew as(String alias) {
        return new MovieCrew(DSL.name(alias), this);
    }

    @Override
    public MovieCrew as(Name alias) {
        return new MovieCrew(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieCrew rename(String name) {
        return new MovieCrew(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieCrew rename(Name name) {
        return new MovieCrew(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
