/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables;


import com.example.springboot.jooqGenerated.Keys;
import com.example.springboot.jooqGenerated.Movies;
import com.example.springboot.jooqGenerated.tables.records.MovieLanguagesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieLanguages extends TableImpl<MovieLanguagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>movies.movie_languages</code>
     */
    public static final MovieLanguages MOVIE_LANGUAGES = new MovieLanguages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieLanguagesRecord> getRecordType() {
        return MovieLanguagesRecord.class;
    }

    /**
     * The column <code>movies.movie_languages.movie_id</code>.
     */
    public final TableField<MovieLanguagesRecord, Integer> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.movie_languages.language_id</code>.
     */
    public final TableField<MovieLanguagesRecord, Integer> LANGUAGE_ID = createField(DSL.name("language_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.movie_languages.language_role_id</code>.
     */
    public final TableField<MovieLanguagesRecord, Integer> LANGUAGE_ROLE_ID = createField(DSL.name("language_role_id"), SQLDataType.INTEGER, this, "");

    private MovieLanguages(Name alias, Table<MovieLanguagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private MovieLanguages(Name alias, Table<MovieLanguagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>movies.movie_languages</code> table reference
     */
    public MovieLanguages(String alias) {
        this(DSL.name(alias), MOVIE_LANGUAGES);
    }

    /**
     * Create an aliased <code>movies.movie_languages</code> table reference
     */
    public MovieLanguages(Name alias) {
        this(alias, MOVIE_LANGUAGES);
    }

    /**
     * Create a <code>movies.movie_languages</code> table reference
     */
    public MovieLanguages() {
        this(DSL.name("movie_languages"), null);
    }

    public <O extends Record> MovieLanguages(Table<O> child, ForeignKey<O, MovieLanguagesRecord> key) {
        super(child, key, MOVIE_LANGUAGES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Movies.MOVIES;
    }

    @Override
    public List<ForeignKey<MovieLanguagesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ML_MOVIE, Keys.FK_ML_LANG, Keys.FK_ML_ROLE);
    }

    private transient Movie _movie;
    private transient Language _language;
    private transient LanguageRole _languageRole;

    /**
     * Get the implicit join path to the <code>movies.movie</code> table.
     */
    public Movie movie() {
        if (_movie == null)
            _movie = new Movie(this, Keys.FK_ML_MOVIE);

        return _movie;
    }

    /**
     * Get the implicit join path to the <code>movies.language</code> table.
     */
    public Language language() {
        if (_language == null)
            _language = new Language(this, Keys.FK_ML_LANG);

        return _language;
    }

    /**
     * Get the implicit join path to the <code>movies.language_role</code>
     * table.
     */
    public LanguageRole languageRole() {
        if (_languageRole == null)
            _languageRole = new LanguageRole(this, Keys.FK_ML_ROLE);

        return _languageRole;
    }

    @Override
    public MovieLanguages as(String alias) {
        return new MovieLanguages(DSL.name(alias), this);
    }

    @Override
    public MovieLanguages as(Name alias) {
        return new MovieLanguages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieLanguages rename(String name) {
        return new MovieLanguages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieLanguages rename(Name name) {
        return new MovieLanguages(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
