/*
 * This file is generated by jOOQ.
 */
package com.example.springboot.jooqGenerated.tables;


import com.example.springboot.jooqGenerated.Keys;
import com.example.springboot.jooqGenerated.Movies;
import com.example.springboot.jooqGenerated.tables.records.ProductionCountryRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductionCountry extends TableImpl<ProductionCountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>movies.production_country</code>
     */
    public static final ProductionCountry PRODUCTION_COUNTRY = new ProductionCountry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductionCountryRecord> getRecordType() {
        return ProductionCountryRecord.class;
    }

    /**
     * The column <code>movies.production_country.movie_id</code>.
     */
    public final TableField<ProductionCountryRecord, Integer> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>movies.production_country.country_id</code>.
     */
    public final TableField<ProductionCountryRecord, Integer> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.INTEGER, this, "");

    private ProductionCountry(Name alias, Table<ProductionCountryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductionCountry(Name alias, Table<ProductionCountryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>movies.production_country</code> table reference
     */
    public ProductionCountry(String alias) {
        this(DSL.name(alias), PRODUCTION_COUNTRY);
    }

    /**
     * Create an aliased <code>movies.production_country</code> table reference
     */
    public ProductionCountry(Name alias) {
        this(alias, PRODUCTION_COUNTRY);
    }

    /**
     * Create a <code>movies.production_country</code> table reference
     */
    public ProductionCountry() {
        this(DSL.name("production_country"), null);
    }

    public <O extends Record> ProductionCountry(Table<O> child, ForeignKey<O, ProductionCountryRecord> key) {
        super(child, key, PRODUCTION_COUNTRY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Movies.MOVIES;
    }

    @Override
    public List<ForeignKey<ProductionCountryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PC_MOVIE, Keys.FK_PC_COUNTRY);
    }

    private transient Movie _movie;
    private transient Country _country;

    /**
     * Get the implicit join path to the <code>movies.movie</code> table.
     */
    public Movie movie() {
        if (_movie == null)
            _movie = new Movie(this, Keys.FK_PC_MOVIE);

        return _movie;
    }

    /**
     * Get the implicit join path to the <code>movies.country</code> table.
     */
    public Country country() {
        if (_country == null)
            _country = new Country(this, Keys.FK_PC_COUNTRY);

        return _country;
    }

    @Override
    public ProductionCountry as(String alias) {
        return new ProductionCountry(DSL.name(alias), this);
    }

    @Override
    public ProductionCountry as(Name alias) {
        return new ProductionCountry(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductionCountry rename(String name) {
        return new ProductionCountry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductionCountry rename(Name name) {
        return new ProductionCountry(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
